[[redirects]]
  from = "/*"
  to = "/error/404"
  status = 404

  from = "/*"
  to = "/error/400"
  status = 400

  from = "/*"
  to = "/error/401"
  status = 401
  
  from = "/*"
  to = "/error/401"
  status = 403
  
  from = "/*"
  to = "/error/405"
  status = 405
  
  from = "/*"
  to = "/error/406"
  status = 406
  
  from = "/*"
  to = "/error/407"
  status = 407
  
  from = "/*"
  to = "/error/408"
  status = 408
  
  from = "/*"
  to = "/error/409"
  status = 409
  
  from = "/*"
  to = "/error/410"
  status = 410
  
  from = "/*"
  to = "/error/411"
  status = 411
  
  from = "/*"
  to = "/error/412"
  status = 412
  
  from = "/*"
  to = "/error/413"
  status = 413
  
  from = "/*"
  to = "/error/414"
  status = 414
  
  from = "/*"
  to = "/error/415"
  status = 415
  
  from = "/*"
  to = "/error/416"
  status = 416
  
  from = "/*"
  to = "/error/417"
  status = 417
